### ISSUE TITLE
NetworkBrowser's netscan freezes when discover Windows 10 shares

### ISSUE THREAD

**Issue by petrkr** [OpenPLi/enigma2-plugins#572]
check  issue here: https://github.com/OpenVisionE2/openvision-development-platform/issues/34#issuecomment-678790162

Tested from command line. Nor about settings on windows site/network I think library should NOT freeze forever when socket get's closed by "TCP RST" flag. It leads to python call took forever and freezes box.

**Comment by WanWizard** [comment]
I've commented there, no need to split the discussion.
