### ISSUE TITLE
Revcam

### ISSUE THREAD

**Issue by gaasim** [OpenPLi/enigma2-plugins#784]
The Revcam emulator is installed, but opens Csat channels very slowly on 19.2E, the same thing is on the Python 2.7 version of OpenPli 8.2 image, while on Python 2.7 OpenPli-develop version it opens Csat channels on 19.2E very quickly. I have tried other images but this Openpli-develop version is by far the fastest.

**Comment by gaasim** [comment]
I’ve tried all the versions of OpenPli 8.2 that came out, and it’s always the same thing with RevCam, and just like I’ve been testing the Python 3 version of OpenPli on the Zgemma H7S receiver since two days ago, from the day they started coming out for that receiver.

**Comment by WanWizard** [comment]
The Python3 image is a test image, not meant for daily use.

OE differences: https://github.com/OpenPLi/openpli-oe-core/compare/release-8.2...develop
Enigma differences: https://github.com/OpenPLi/enigma2/compare/release-8.2...develop
( and some of these have been backported so there is less of a difference than this )

I have no clue what RevCam is, so I can't comment on that. A quick Google shows it's used for watching TV illegally, which is something we don't support anyway. So I consider this case closed.
