### ISSUE TITLE
How do I build / test the blindscan plugin?

### ISSUE THREAD

**Issue by crusty-dave** [OpenPLi/enigma2-plugins#856]
The blindscan plugin isn't working with the add-on tuner for the GigaBlue 4K UHD receiver.  Note that this is on C-band, I haven't tried Ku-band yet.  I am running OpenATV 7.1 latest.

I am willing to debug it, I believe that I see the issue looking at the code, but I am not sure how start?  First I want to build the existing code and add some debug logging.

Are the print statements copied to a log?  If so, what is the path.

**Comment by crusty-dave** [comment]
It looks like I am in the wrong repo, I guess I need the oe-alliance plugin for OpenATV.

I guess I should try the OpenPLi image.

**Comment by kueken** [comment]
The 'Blindscan' functionality is added by the manufacturer as a driver.

It is certainly better to ask in the respective forum.
https://www.opena.tv/
https://forums.openpli.org/
